title: Andy Site
author: andyred1
email: iphonemaster840@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to use Github Pages by making this jekyll website.
theme: minima
# social links
twitter_username: AndyRed1012 # DO NOT include the @ character, or else the build will fail!
github_username:  andyred1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
